// <auto-generated />
using System;
using Administrator.Core;
using Administrator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Administrator.Database.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20240816161947_Guild_MaxLuaCommands")]
    partial class Guild_MaxLuaCommands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Administrator.Database.Attachment", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.HasKey("Key")
                        .HasName("pk_attachment");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.AutomaticPunishment", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("DemeritPoints")
                        .HasColumnType("integer")
                        .HasColumnName("demerit_points");

                    b.Property<TimeSpan?>("PunishmentDuration")
                        .HasColumnType("interval")
                        .HasColumnName("punishment_duration");

                    b.Property<int>("PunishmentType")
                        .HasColumnType("integer")
                        .HasColumnName("punishment_type");

                    b.HasKey("GuildId", "DemeritPoints")
                        .HasName("pk_automatic_punishments");

                    b.ToTable("automatic_punishments", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.ButtonRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("Emoji")
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<int?>("ExclusiveGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("exclusive_group_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<byte>("Style")
                        .HasColumnType("smallint")
                        .HasColumnName("style");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_button_roles");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_button_roles_guild_id");

                    b.ToTable("button_roles", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.EmojiStats", b =>
                {
                    b.Property<long>("EmojiId")
                        .HasColumnType("bigint")
                        .HasColumnName("emoji_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("EmojiId")
                        .HasName("pk_emoji_stats");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_emoji_stats_guild_id");

                    b.ToTable("emoji_stats", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.ForumAutoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("boolean")
                        .HasColumnName("is_regex");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_auto_tags");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_auto_tags_channel_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_auto_tags_guild_id");

                    b.ToTable("auto_tags", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Guild", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<byte[]>("ApiKeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_hash");

                    b.Property<byte[]>("ApiKeySalt")
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_salt");

                    b.Property<long[]>("AutoQuoteExemptChannelIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("auto_quote_exempt_channel_ids");

                    b.Property<string>("CustomPunishmentText")
                        .HasColumnType("text")
                        .HasColumnName("custom_punishment_text");

                    b.Property<TimeSpan?>("CustomXpInterval")
                        .HasColumnType("interval")
                        .HasColumnName("custom_xp_interval");

                    b.Property<int?>("CustomXpRate")
                        .HasColumnType("integer")
                        .HasColumnName("custom_xp_rate");

                    b.Property<int>("DefaultBanPruneDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_ban_prune_days");

                    b.Property<int>("DefaultWarningDemeritPoints")
                        .HasColumnType("integer")
                        .HasColumnName("default_warning_demerit_points");

                    b.Property<TimeSpan?>("DemeritPointsDecayInterval")
                        .HasColumnType("interval")
                        .HasColumnName("demerit_points_decay_interval");

                    b.Property<bool>("DmGreetingMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("dm_greeting_message");

                    b.Property<JsonMessage>("GoodbyeMessage")
                        .HasColumnType("jsonb")
                        .HasColumnName("goodbye_message");

                    b.Property<JsonMessage>("GreetingMessage")
                        .HasColumnType("jsonb")
                        .HasColumnName("greeting_message");

                    b.Property<long?>("JoinRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("join_role_id");

                    b.Property<string>("LevelUpEmoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level_up_emoji");

                    b.Property<int>("MaxLuaCommands")
                        .HasColumnType("integer")
                        .HasColumnName("max_lua_commands");

                    b.Property<int?>("MaximumTagsPerUser")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_tags_per_user");

                    b.Property<int>("Settings")
                        .HasColumnType("integer")
                        .HasColumnName("settings");

                    b.Property<bool>("WasVisited")
                        .HasColumnType("boolean")
                        .HasColumnName("was_visited");

                    b.Property<long[]>("XpExemptChannelIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("xp_exempt_channel_ids");

                    b.HasKey("GuildId")
                        .HasName("pk_guilds");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_highlights");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_highlights_author_id");

                    b.ToTable("highlights", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.InviteFilterExemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExemptionType")
                        .HasColumnType("integer")
                        .HasColumnName("exemption_type");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_invite_filter_exemptions");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_invite_filter_exemptions_guild_id");

                    b.ToTable("invite_filter_exemptions", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.LoggingChannel", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.HasKey("GuildId", "EventType")
                        .HasName("pk_logging_channels");

                    b.ToTable("logging_channels", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.LuaCommand", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("Command")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("command");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("metadata");

                    b.Property<byte[]>("Persistence")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("persistence");

                    b.HasKey("GuildId", "Name")
                        .HasName("pk_lua_commands");

                    b.ToTable("lua_commands", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Member", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user");

                    b.Property<string>("Blurb")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blurb");

                    b.Property<int>("DemeritPoints")
                        .HasColumnType("integer")
                        .HasColumnName("demerit_points");

                    b.Property<DateTimeOffset?>("LastDemeritPointDecay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_demerit_point_decay");

                    b.Property<DateTimeOffset>("LastLevelUp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_level_up");

                    b.Property<DateTimeOffset>("LastXpGain")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_xp_gain");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_members");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DmChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("dm_channel_id");

                    b.Property<long?>("DmMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("dm_message_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long?>("LogChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_channel_id");

                    b.Property<long?>("LogMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_message_id");

                    b.Property<UserSnapshot>("Moderator")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("moderator");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<UserSnapshot>("Target")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("target");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_punishments");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_punishments_attachment_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_punishments_guild_id");

                    b.ToTable("punishments", (string)null);

                    b.HasDiscriminator<int>("type").IsComplete(true);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Administrator.Database.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<double?>("RepeatInterval")
                        .HasColumnType("double precision")
                        .HasColumnName("repeat_interval");

                    b.Property<int?>("RepeatMode")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_mode");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_reminders_author_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_reminders_expires_at");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.RoleLevelReward", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<long[]>("GrantedRoleIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("granted_role_ids");

                    b.Property<long[]>("RevokedRoleIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("revoked_role_ids");

                    b.HasKey("GuildId", "Tier", "Level")
                        .HasName("pk_level_rewards");

                    b.ToTable("level_rewards", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Tag", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<JsonMessage>("Message")
                        .HasColumnType("jsonb")
                        .HasColumnName("message");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<int>("Uses")
                        .HasColumnType("integer")
                        .HasColumnName("uses");

                    b.HasKey("GuildId", "Name")
                        .HasName("pk_tags");

                    b.HasIndex("Aliases")
                        .HasDatabaseName("ix_tags_aliases");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_tags_attachment_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_tags_owner_id");

                    b.HasIndex("GuildId", "OwnerId")
                        .HasDatabaseName("ix_tags_guild_id_owner_id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.TagLink", b =>
                {
                    b.Property<string>("From")
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("To")
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsEphemeral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ephemeral");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<byte>("Style")
                        .HasColumnType("smallint")
                        .HasColumnName("style");

                    b.HasKey("From", "To")
                        .HasName("pk_linked_tags");

                    b.HasIndex("From")
                        .HasDatabaseName("ix_linked_tags_from");

                    b.ToTable("linked_tags", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.User", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user");

                    b.Property<long[]>("BlacklistedHighlightChannelIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("blacklisted_highlight_channel_ids");

                    b.Property<long[]>("BlacklistedHighlightUserIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("blacklisted_highlight_user_ids");

                    b.Property<DateTimeOffset?>("HighlightsSnoozedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("highlights_snoozed_until");

                    b.Property<DateTimeOffset>("LastLevelUp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_level_up");

                    b.Property<DateTimeOffset>("LastXpGain")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_xp_gain");

                    b.Property<TimeSpan>("ResumeHighlightsAfterInterval")
                        .HasColumnType("interval")
                        .HasColumnName("resume_highlights_after_interval");

                    b.Property<int>("ResumeHighlightsAfterMessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("resume_highlights_after_message_count");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.Property<bool>("WasSentInitialJoinMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("was_sent_initial_join_message");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Kick", b =>
                {
                    b.HasBaseType("Administrator.Database.Punishment");

                    b.ToTable("punishments", (string)null);

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Administrator.Database.RevocablePunishment", b =>
                {
                    b.HasBaseType("Administrator.Database.Punishment");

                    b.Property<long?>("AppealChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("appeal_channel_id");

                    b.Property<long?>("AppealMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("appeal_message_id");

                    b.Property<int?>("AppealStatus")
                        .HasColumnType("integer")
                        .HasColumnName("appeal_status");

                    b.Property<string>("AppealText")
                        .HasColumnType("text")
                        .HasColumnName("appeal_text");

                    b.Property<DateTimeOffset?>("AppealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appealed_at");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<UserSnapshot>("Revoker")
                        .HasColumnType("jsonb")
                        .HasColumnName("revoker");

                    b.ToTable("punishments", (string)null);
                });

            modelBuilder.Entity("Administrator.Database.Warning", b =>
                {
                    b.HasBaseType("Administrator.Database.Punishment");

                    b.Property<int?>("AdditionalPunishmentId")
                        .HasColumnType("integer")
                        .HasColumnName("additional_punishment_id");

                    b.Property<int>("DemeritPointSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("demerit_point_snapshot");

                    b.Property<int>("DemeritPoints")
                        .HasColumnType("integer")
                        .HasColumnName("demerit_points");

                    b.HasIndex("AdditionalPunishmentId")
                        .HasDatabaseName("ix_punishments_additional_punishment_id");

                    b.ToTable("punishments", (string)null);

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Administrator.Database.Ban", b =>
                {
                    b.HasBaseType("Administrator.Database.RevocablePunishment");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("MessagePruneDays")
                        .HasColumnType("integer")
                        .HasColumnName("message_prune_days");

                    b.ToTable("punishments", null, t =>
                        {
                            t.Property("ExpiresAt")
                                .HasColumnName("ban_expires_at");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Administrator.Database.Block", b =>
                {
                    b.HasBaseType("Administrator.Database.RevocablePunishment");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal?>("PreviousChannelAllowPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("previous_channel_allow_permissions");

                    b.Property<decimal?>("PreviousChannelDenyPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("previous_channel_deny_permissions");

                    b.ToTable("punishments", (string)null);

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Administrator.Database.TimedRole", b =>
                {
                    b.HasBaseType("Administrator.Database.RevocablePunishment");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.ToTable("punishments", null, t =>
                        {
                            t.Property("ExpiresAt")
                                .HasColumnName("timed_role_expires_at");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Administrator.Database.Timeout", b =>
                {
                    b.HasBaseType("Administrator.Database.RevocablePunishment");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("WasManuallyRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("was_manually_revoked");

                    b.ToTable("punishments", null, t =>
                        {
                            t.Property("ExpiresAt")
                                .HasColumnName("timeout_expires_at");
                        });

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Administrator.Database.AutomaticPunishment", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("AutomaticPunishments")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_automatic_punishments_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.ButtonRole", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("ButtonRoles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_button_roles_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.EmojiStats", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("EmojiStats")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_emoji_stats_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.ForumAutoTag", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("ForumAutoTags")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_auto_tags_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.Highlight", b =>
                {
                    b.HasOne("Administrator.Database.User", "Author")
                        .WithMany("Highlights")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_highlights_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Administrator.Database.InviteFilterExemption", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("InviteFilterExemptions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_invite_filter_exemptions_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.LoggingChannel", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("LoggingChannels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_logging_channels_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.LuaCommand", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("LuaCommands")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_lua_commands_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.Punishment", b =>
                {
                    b.HasOne("Administrator.Database.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .HasConstraintName("fk_punishments_attachment_attachment_id");

                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("Punishments")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_punishments_guilds_guild_id");

                    b.Navigation("Attachment");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.Reminder", b =>
                {
                    b.HasOne("Administrator.Database.User", "Author")
                        .WithMany("Reminders")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Administrator.Database.RoleLevelReward", b =>
                {
                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("LevelRewards")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_level_rewards_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Administrator.Database.Tag", b =>
                {
                    b.HasOne("Administrator.Database.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .HasConstraintName("fk_tags_attachment_attachment_id");

                    b.HasOne("Administrator.Database.Guild", "Guild")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tags_guilds_guild_id");

                    b.HasOne("Administrator.Database.Member", "Owner")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_tags_members_guild_id_owner_id");

                    b.Navigation("Attachment");

                    b.Navigation("Guild");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Administrator.Database.Warning", b =>
                {
                    b.HasOne("Administrator.Database.Punishment", "AdditionalPunishment")
                        .WithMany()
                        .HasForeignKey("AdditionalPunishmentId")
                        .HasConstraintName("fk_punishments_punishments_additional_punishment_id");

                    b.Navigation("AdditionalPunishment");
                });

            modelBuilder.Entity("Administrator.Database.Guild", b =>
                {
                    b.Navigation("AutomaticPunishments");

                    b.Navigation("ButtonRoles");

                    b.Navigation("EmojiStats");

                    b.Navigation("ForumAutoTags");

                    b.Navigation("InviteFilterExemptions");

                    b.Navigation("LevelRewards");

                    b.Navigation("LoggingChannels");

                    b.Navigation("LuaCommands");

                    b.Navigation("Punishments");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Administrator.Database.Member", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Administrator.Database.User", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
