<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Disqord.Bot" />
      <PackageReference Include="Humanizer.Core" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Administrator.Core\Administrator.Core.csproj" />
      <ProjectReference Include="..\Administrator.Database\Administrator.Database.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Attributes\" />
      <Folder Include="Parsers\" />
    </ItemGroup>

</Project>
